# leap year 


def isleapyear (year):
  if(year % 4==0 and year % year% 100!=0)or year %400 ==0:
    return True 
  else: 
    return False

year=2012

ifisleapyear(year):
  print('{}is a leap year.'.format(year))
else:
  print({}is not a leap.'.format (year))
